app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('bindu/',bindu,name='bindu'),
    path('mahitha/',mahitha,name='mahitha'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('madhusri/',madhusri,name='madhusri'),
    path('srividya/',srividya,name='srividya'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path("admin/", admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def bindu(request):
    return render(request,'bindu.html')
def mahitha(request):
    return render(request,'mahitha.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def madhusri(request):
    return render(request,'madhusri.html')
def srividya(request):
    return render(request,'srividya.html')

templates/bindu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO BINDU PAGE</h1>
    <a href="{% url 'app2:madhusri' %}">NAVIGATE TO MADHUSRI PAGE</a>
</body>
</html>

templates/madhusri.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO MADHUSRI PAGE</h1>
    <a href="{% url  'app1:bindu' %}">NAVIGATE TO BINDU PAGE</a>
</body>
</html>

templates/mahitha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO MAHITHA PAGE</h1>
    <a href="{% url 'app2:srividya' %}">NAVIGATE TO SRIVIDYA PAGE</a>
</body>
</html>

templates/srividya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO SRIVIDYA PAGE</h1>
    <a href="{% url  'app1:mahitha' %}">NAVIGATE TO MAHITHA PAGE</a>
</body>
</html>